// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package qrs

import ()

type Message struct {
	ID          int64  `json:"id"`
	Content     string `json:"content"`
	RecepientID int64  `json:"recepient_id"`
	SenderID    int64  `json:"sender_id"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}
